//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themebitch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Information
    {
        public Information()
        {
            this.Comments = new HashSet<Comment>();
            this.Projects = new HashSet<Project>();
            this.Subtasks = new HashSet<Subtask>();
            this.Tasks = new HashSet<Task>();
            this.Teams = new HashSet<Team>();
        }
    
        public int InformationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ContactNumber { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string Username { get; set; }
        public string Pword { get; set; }
        public string Specialty { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Subtask> Subtasks { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
