//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themebitch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Comments = new HashSet<Comment>();
            this.Invites = new HashSet<Invite>();
            this.Tasks = new HashSet<Task>();
            this.Teams = new HashSet<Team>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectTitle { get; set; }
        public System.DateTime DueDate { get; set; }
        public string ProjectDescription { get; set; }
        public string ProjectStatus { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string ProjectPriority { get; set; }
        public int InformationID { get; set; }

        public string FileUploaded { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Information Information { get; set; }
        public virtual ICollection<Invite> Invites { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<Team> Teams { get; set; }
    }
}
