//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace themebitch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subtask
    {
        public int SubtaskID { get; set; }
        public string SubtaskTitle { get; set; }
        public System.DateTime DueDate { get; set; }
        public string SubtaskDescription { get; set; }
        public string SubtaskStatus { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public string SubtaskPriority { get; set; }
        public int InformationID { get; set; }
        public int TaskID { get; set; }
        public string FileUploaded { get; set; }
        public virtual Information Information { get; set; }
        public virtual Task Task { get; set; }
    }
}
